[book]
authors = ["Duncan McGreggor"]
language = "en"
src = "src"
title = "The Zylisp Guide"
description = "A guide for programmers who are new to Zylisp, Lisp or even Go"

[build]
build-dir = "book"

[preprocessor.index]

[preprocessor.links]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "lfe-pdp"
preferred-dark-theme = "lfe-pdp"
additional-js = ["js/mermaid.min.js", "js/mermaid-init.js"]
git-repository-url = "https://github.com/cnbbooks/lfe-manual"
[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.fold]
enable = true
